export * from './app-login/app-login.component'
export * from './app-device-add/app-device-add.component'
export * from './app-device-list/app-device-list.component'
export * from './app-device-detail/app-device-detail.component'
export * from './app-setting/app-setting.component'
export * from './app-setting-wifi/app-setting-wifi.component'
